apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: default
data:
  application.properties: |-
    spring.main.banner-mode=OFF
    spring.datasource.url=jdbc:h2:file:/volume-mount/h2-data;DB_CLOSE_ON_EXIT=FALSE
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=update
    config-map.message=Reading properties from config map!